/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminCreatePostRouteImport } from './routes/admin/create-post'
import { Route as AuthorIndexRouteImport } from './routes/author/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuCategoryRouteImport } from './routes/menu.$category'
import { Route as MenuBeveragesRouteImport } from './routes/menu.beverages'
import { Route as MenuBiscuitsRouteImport } from './routes/menu.biscuits'
import { Route as MenuBurgersRouteImport } from './routes/menu.burgers'
import { Route as MenuClassicDinnersRouteImport } from './routes/menu.classic-dinners'
import { Route as MenuHashbrownsRouteImport } from './routes/menu.hashbrowns'
import { Route as MenuSandwichesRouteImport } from './routes/menu.sandwiches'
import { Route as MenuSidesRouteImport } from './routes/menu.sides'
import { Route as MenuTexasMeltsRouteImport } from './routes/menu.texas-melts'
import { Route as LocationsStateIndexRouteImport } from './routes/locations.$state.index'
import { Route as LocationsStateCityRouteImport } from './routes/locations.$state.$city'
import { Route as MenuCategoryIndexRouteImport } from './routes/menu.$category.index'
import { Route as MenuCategorySlugRouteImport } from './routes/menu.$category.$slug'
import { Route as MenuAllStarSpecialIndexRouteImport } from './routes/menu.all-star-special.index'
import { Route as MenuBeveragesIndexRouteImport } from './routes/menu.beverages.index'
import { Route as MenuBiscuitsIndexRouteImport } from './routes/menu.biscuits.index'
import { Route as MenuBreakfastSandwichesIndexRouteImport } from './routes/menu.breakfast-sandwiches.index'
import { Route as MenuBreakfastIndexRouteImport } from './routes/menu.breakfast.index'
import { Route as MenuBurgersIndexRouteImport } from './routes/menu.burgers.index'
import { Route as MenuClassicDinnersIndexRouteImport } from './routes/menu.classic-dinners.index'
import { Route as MenuEggBreakfastsIndexRouteImport } from './routes/menu.egg-breakfasts.index'
import { Route as MenuHashbrownBowlsIndexRouteImport } from './routes/menu.hashbrown-bowls.index'
import { Route as MenuHashbrownsIndexRouteImport } from './routes/menu.hashbrowns.index'
import { Route as MenuOmeletsIndexRouteImport } from './routes/menu.omelets.index'
import { Route as MenuSandwichesIndexRouteImport } from './routes/menu.sandwiches.index'
import { Route as MenuSidesIndexRouteImport } from './routes/menu.sides.index'
import { Route as MenuTexasMeltsIndexRouteImport } from './routes/menu.texas-melts.index'
import { Route as MenuWafflesIndexRouteImport } from './routes/menu.waffles.index'
import { Route as MenuCategoryPagePageRouteImport } from './routes/menu.$category.page.$page'
import { Route as MenuAllStarSpecialPagePageRouteImport } from './routes/menu.all-star-special.page.$page'
import { Route as MenuBeveragesPagePageRouteImport } from './routes/menu.beverages.page.$page'
import { Route as MenuBreakfastSandwichesPagePageRouteImport } from './routes/menu.breakfast-sandwiches.page.$page'
import { Route as MenuHashbrownsPagePageRouteImport } from './routes/menu.hashbrowns.page.$page'
import { Route as MenuSidesPagePageRouteImport } from './routes/menu.sides.page.$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreatePostRoute = AdminCreatePostRouteImport.update({
  id: '/admin/create-post',
  path: '/admin/create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuCategoryRoute = MenuCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => MenuRoute,
} as any)
const MenuBeveragesRoute = MenuBeveragesRouteImport.update({
  id: '/beverages',
  path: '/beverages',
  getParentRoute: () => MenuRoute,
} as any)
const MenuBiscuitsRoute = MenuBiscuitsRouteImport.update({
  id: '/biscuits',
  path: '/biscuits',
  getParentRoute: () => MenuRoute,
} as any)
const MenuBurgersRoute = MenuBurgersRouteImport.update({
  id: '/burgers',
  path: '/burgers',
  getParentRoute: () => MenuRoute,
} as any)
const MenuClassicDinnersRoute = MenuClassicDinnersRouteImport.update({
  id: '/classic-dinners',
  path: '/classic-dinners',
  getParentRoute: () => MenuRoute,
} as any)
const MenuHashbrownsRoute = MenuHashbrownsRouteImport.update({
  id: '/hashbrowns',
  path: '/hashbrowns',
  getParentRoute: () => MenuRoute,
} as any)
const MenuSandwichesRoute = MenuSandwichesRouteImport.update({
  id: '/sandwiches',
  path: '/sandwiches',
  getParentRoute: () => MenuRoute,
} as any)
const MenuSidesRoute = MenuSidesRouteImport.update({
  id: '/sides',
  path: '/sides',
  getParentRoute: () => MenuRoute,
} as any)
const MenuTexasMeltsRoute = MenuTexasMeltsRouteImport.update({
  id: '/texas-melts',
  path: '/texas-melts',
  getParentRoute: () => MenuRoute,
} as any)
const LocationsStateIndexRoute = LocationsStateIndexRouteImport.update({
  id: '/locations/$state/',
  path: '/locations/$state/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsStateCityRoute = LocationsStateCityRouteImport.update({
  id: '/locations/$state/$city',
  path: '/locations/$state/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuCategoryIndexRoute = MenuCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuCategoryRoute,
} as any)
const MenuCategorySlugRoute = MenuCategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MenuCategoryRoute,
} as any)
const MenuAllStarSpecialIndexRoute = MenuAllStarSpecialIndexRouteImport.update({
  id: '/all-star-special/',
  path: '/all-star-special/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuBeveragesIndexRoute = MenuBeveragesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuBeveragesRoute,
} as any)
const MenuBiscuitsIndexRoute = MenuBiscuitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuBiscuitsRoute,
} as any)
const MenuBreakfastSandwichesIndexRoute =
  MenuBreakfastSandwichesIndexRouteImport.update({
    id: '/breakfast-sandwiches/',
    path: '/breakfast-sandwiches/',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuBreakfastIndexRoute = MenuBreakfastIndexRouteImport.update({
  id: '/breakfast/',
  path: '/breakfast/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuBurgersIndexRoute = MenuBurgersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuBurgersRoute,
} as any)
const MenuClassicDinnersIndexRoute = MenuClassicDinnersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuClassicDinnersRoute,
} as any)
const MenuEggBreakfastsIndexRoute = MenuEggBreakfastsIndexRouteImport.update({
  id: '/egg-breakfasts/',
  path: '/egg-breakfasts/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuHashbrownBowlsIndexRoute = MenuHashbrownBowlsIndexRouteImport.update({
  id: '/hashbrown-bowls/',
  path: '/hashbrown-bowls/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuHashbrownsIndexRoute = MenuHashbrownsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuHashbrownsRoute,
} as any)
const MenuOmeletsIndexRoute = MenuOmeletsIndexRouteImport.update({
  id: '/omelets/',
  path: '/omelets/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuSandwichesIndexRoute = MenuSandwichesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuSandwichesRoute,
} as any)
const MenuSidesIndexRoute = MenuSidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuSidesRoute,
} as any)
const MenuTexasMeltsIndexRoute = MenuTexasMeltsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuTexasMeltsRoute,
} as any)
const MenuWafflesIndexRoute = MenuWafflesIndexRouteImport.update({
  id: '/waffles/',
  path: '/waffles/',
  getParentRoute: () => MenuRoute,
} as any)
const MenuCategoryPagePageRoute = MenuCategoryPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => MenuCategoryRoute,
} as any)
const MenuAllStarSpecialPagePageRoute =
  MenuAllStarSpecialPagePageRouteImport.update({
    id: '/all-star-special/page/$page',
    path: '/all-star-special/page/$page',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuBeveragesPagePageRoute = MenuBeveragesPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => MenuBeveragesRoute,
} as any)
const MenuBreakfastSandwichesPagePageRoute =
  MenuBreakfastSandwichesPagePageRouteImport.update({
    id: '/breakfast-sandwiches/page/$page',
    path: '/breakfast-sandwiches/page/$page',
    getParentRoute: () => MenuRoute,
  } as any)
const MenuHashbrownsPagePageRoute = MenuHashbrownsPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => MenuHashbrownsRoute,
} as any)
const MenuSidesPagePageRoute = MenuSidesPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => MenuSidesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/menu': typeof MenuRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/nutrition': typeof NutritionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/create-post': typeof AdminCreatePostRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/menu/$category': typeof MenuCategoryRouteWithChildren
  '/menu/beverages': typeof MenuBeveragesRouteWithChildren
  '/menu/biscuits': typeof MenuBiscuitsRouteWithChildren
  '/menu/burgers': typeof MenuBurgersRouteWithChildren
  '/menu/classic-dinners': typeof MenuClassicDinnersRouteWithChildren
  '/menu/hashbrowns': typeof MenuHashbrownsRouteWithChildren
  '/menu/sandwiches': typeof MenuSandwichesRouteWithChildren
  '/menu/sides': typeof MenuSidesRouteWithChildren
  '/menu/texas-melts': typeof MenuTexasMeltsRouteWithChildren
  '/author/': typeof AuthorIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/locations/$state/$city': typeof LocationsStateCityRoute
  '/menu/$category/$slug': typeof MenuCategorySlugRoute
  '/locations/$state/': typeof LocationsStateIndexRoute
  '/menu/$category/': typeof MenuCategoryIndexRoute
  '/menu/all-star-special/': typeof MenuAllStarSpecialIndexRoute
  '/menu/beverages/': typeof MenuBeveragesIndexRoute
  '/menu/biscuits/': typeof MenuBiscuitsIndexRoute
  '/menu/breakfast-sandwiches/': typeof MenuBreakfastSandwichesIndexRoute
  '/menu/breakfast/': typeof MenuBreakfastIndexRoute
  '/menu/burgers/': typeof MenuBurgersIndexRoute
  '/menu/classic-dinners/': typeof MenuClassicDinnersIndexRoute
  '/menu/egg-breakfasts/': typeof MenuEggBreakfastsIndexRoute
  '/menu/hashbrown-bowls/': typeof MenuHashbrownBowlsIndexRoute
  '/menu/hashbrowns/': typeof MenuHashbrownsIndexRoute
  '/menu/omelets/': typeof MenuOmeletsIndexRoute
  '/menu/sandwiches/': typeof MenuSandwichesIndexRoute
  '/menu/sides/': typeof MenuSidesIndexRoute
  '/menu/texas-melts/': typeof MenuTexasMeltsIndexRoute
  '/menu/waffles/': typeof MenuWafflesIndexRoute
  '/menu/$category/page/$page': typeof MenuCategoryPagePageRoute
  '/menu/all-star-special/page/$page': typeof MenuAllStarSpecialPagePageRoute
  '/menu/beverages/page/$page': typeof MenuBeveragesPagePageRoute
  '/menu/breakfast-sandwiches/page/$page': typeof MenuBreakfastSandwichesPagePageRoute
  '/menu/hashbrowns/page/$page': typeof MenuHashbrownsPagePageRoute
  '/menu/sides/page/$page': typeof MenuSidesPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/methodology': typeof MethodologyRoute
  '/nutrition': typeof NutritionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/create-post': typeof AdminCreatePostRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/author': typeof AuthorIndexRoute
  '/blog': typeof BlogIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/menu': typeof MenuIndexRoute
  '/locations/$state/$city': typeof LocationsStateCityRoute
  '/menu/$category/$slug': typeof MenuCategorySlugRoute
  '/locations/$state': typeof LocationsStateIndexRoute
  '/menu/$category': typeof MenuCategoryIndexRoute
  '/menu/all-star-special': typeof MenuAllStarSpecialIndexRoute
  '/menu/beverages': typeof MenuBeveragesIndexRoute
  '/menu/biscuits': typeof MenuBiscuitsIndexRoute
  '/menu/breakfast-sandwiches': typeof MenuBreakfastSandwichesIndexRoute
  '/menu/breakfast': typeof MenuBreakfastIndexRoute
  '/menu/burgers': typeof MenuBurgersIndexRoute
  '/menu/classic-dinners': typeof MenuClassicDinnersIndexRoute
  '/menu/egg-breakfasts': typeof MenuEggBreakfastsIndexRoute
  '/menu/hashbrown-bowls': typeof MenuHashbrownBowlsIndexRoute
  '/menu/hashbrowns': typeof MenuHashbrownsIndexRoute
  '/menu/omelets': typeof MenuOmeletsIndexRoute
  '/menu/sandwiches': typeof MenuSandwichesIndexRoute
  '/menu/sides': typeof MenuSidesIndexRoute
  '/menu/texas-melts': typeof MenuTexasMeltsIndexRoute
  '/menu/waffles': typeof MenuWafflesIndexRoute
  '/menu/$category/page/$page': typeof MenuCategoryPagePageRoute
  '/menu/all-star-special/page/$page': typeof MenuAllStarSpecialPagePageRoute
  '/menu/beverages/page/$page': typeof MenuBeveragesPagePageRoute
  '/menu/breakfast-sandwiches/page/$page': typeof MenuBreakfastSandwichesPagePageRoute
  '/menu/hashbrowns/page/$page': typeof MenuHashbrownsPagePageRoute
  '/menu/sides/page/$page': typeof MenuSidesPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/menu': typeof MenuRouteWithChildren
  '/methodology': typeof MethodologyRoute
  '/nutrition': typeof NutritionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/create-post': typeof AdminCreatePostRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/menu/$category': typeof MenuCategoryRouteWithChildren
  '/menu/beverages': typeof MenuBeveragesRouteWithChildren
  '/menu/biscuits': typeof MenuBiscuitsRouteWithChildren
  '/menu/burgers': typeof MenuBurgersRouteWithChildren
  '/menu/classic-dinners': typeof MenuClassicDinnersRouteWithChildren
  '/menu/hashbrowns': typeof MenuHashbrownsRouteWithChildren
  '/menu/sandwiches': typeof MenuSandwichesRouteWithChildren
  '/menu/sides': typeof MenuSidesRouteWithChildren
  '/menu/texas-melts': typeof MenuTexasMeltsRouteWithChildren
  '/author/': typeof AuthorIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/locations/$state/$city': typeof LocationsStateCityRoute
  '/menu/$category/$slug': typeof MenuCategorySlugRoute
  '/locations/$state/': typeof LocationsStateIndexRoute
  '/menu/$category/': typeof MenuCategoryIndexRoute
  '/menu/all-star-special/': typeof MenuAllStarSpecialIndexRoute
  '/menu/beverages/': typeof MenuBeveragesIndexRoute
  '/menu/biscuits/': typeof MenuBiscuitsIndexRoute
  '/menu/breakfast-sandwiches/': typeof MenuBreakfastSandwichesIndexRoute
  '/menu/breakfast/': typeof MenuBreakfastIndexRoute
  '/menu/burgers/': typeof MenuBurgersIndexRoute
  '/menu/classic-dinners/': typeof MenuClassicDinnersIndexRoute
  '/menu/egg-breakfasts/': typeof MenuEggBreakfastsIndexRoute
  '/menu/hashbrown-bowls/': typeof MenuHashbrownBowlsIndexRoute
  '/menu/hashbrowns/': typeof MenuHashbrownsIndexRoute
  '/menu/omelets/': typeof MenuOmeletsIndexRoute
  '/menu/sandwiches/': typeof MenuSandwichesIndexRoute
  '/menu/sides/': typeof MenuSidesIndexRoute
  '/menu/texas-melts/': typeof MenuTexasMeltsIndexRoute
  '/menu/waffles/': typeof MenuWafflesIndexRoute
  '/menu/$category/page/$page': typeof MenuCategoryPagePageRoute
  '/menu/all-star-special/page/$page': typeof MenuAllStarSpecialPagePageRoute
  '/menu/beverages/page/$page': typeof MenuBeveragesPagePageRoute
  '/menu/breakfast-sandwiches/page/$page': typeof MenuBreakfastSandwichesPagePageRoute
  '/menu/hashbrowns/page/$page': typeof MenuHashbrownsPagePageRoute
  '/menu/sides/page/$page': typeof MenuSidesPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/menu'
    | '/methodology'
    | '/nutrition'
    | '/privacy-policy'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/blog'
    | '/admin/create-post'
    | '/blog/$slug'
    | '/menu/$category'
    | '/menu/beverages'
    | '/menu/biscuits'
    | '/menu/burgers'
    | '/menu/classic-dinners'
    | '/menu/hashbrowns'
    | '/menu/sandwiches'
    | '/menu/sides'
    | '/menu/texas-melts'
    | '/author/'
    | '/blog/'
    | '/locations/'
    | '/menu/'
    | '/locations/$state/$city'
    | '/menu/$category/$slug'
    | '/locations/$state/'
    | '/menu/$category/'
    | '/menu/all-star-special/'
    | '/menu/beverages/'
    | '/menu/biscuits/'
    | '/menu/breakfast-sandwiches/'
    | '/menu/breakfast/'
    | '/menu/burgers/'
    | '/menu/classic-dinners/'
    | '/menu/egg-breakfasts/'
    | '/menu/hashbrown-bowls/'
    | '/menu/hashbrowns/'
    | '/menu/omelets/'
    | '/menu/sandwiches/'
    | '/menu/sides/'
    | '/menu/texas-melts/'
    | '/menu/waffles/'
    | '/menu/$category/page/$page'
    | '/menu/all-star-special/page/$page'
    | '/menu/beverages/page/$page'
    | '/menu/breakfast-sandwiches/page/$page'
    | '/menu/hashbrowns/page/$page'
    | '/menu/sides/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/methodology'
    | '/nutrition'
    | '/privacy-policy'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/blog'
    | '/admin/create-post'
    | '/blog/$slug'
    | '/author'
    | '/blog'
    | '/locations'
    | '/menu'
    | '/locations/$state/$city'
    | '/menu/$category/$slug'
    | '/locations/$state'
    | '/menu/$category'
    | '/menu/all-star-special'
    | '/menu/beverages'
    | '/menu/biscuits'
    | '/menu/breakfast-sandwiches'
    | '/menu/breakfast'
    | '/menu/burgers'
    | '/menu/classic-dinners'
    | '/menu/egg-breakfasts'
    | '/menu/hashbrown-bowls'
    | '/menu/hashbrowns'
    | '/menu/omelets'
    | '/menu/sandwiches'
    | '/menu/sides'
    | '/menu/texas-melts'
    | '/menu/waffles'
    | '/menu/$category/page/$page'
    | '/menu/all-star-special/page/$page'
    | '/menu/beverages/page/$page'
    | '/menu/breakfast-sandwiches/page/$page'
    | '/menu/hashbrowns/page/$page'
    | '/menu/sides/page/$page'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/editorial-policy'
    | '/faq'
    | '/menu'
    | '/methodology'
    | '/nutrition'
    | '/privacy-policy'
    | '/search'
    | '/sitemap'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/blog'
    | '/admin/create-post'
    | '/blog/$slug'
    | '/menu/$category'
    | '/menu/beverages'
    | '/menu/biscuits'
    | '/menu/burgers'
    | '/menu/classic-dinners'
    | '/menu/hashbrowns'
    | '/menu/sandwiches'
    | '/menu/sides'
    | '/menu/texas-melts'
    | '/author/'
    | '/blog/'
    | '/locations/'
    | '/menu/'
    | '/locations/$state/$city'
    | '/menu/$category/$slug'
    | '/locations/$state/'
    | '/menu/$category/'
    | '/menu/all-star-special/'
    | '/menu/beverages/'
    | '/menu/biscuits/'
    | '/menu/breakfast-sandwiches/'
    | '/menu/breakfast/'
    | '/menu/burgers/'
    | '/menu/classic-dinners/'
    | '/menu/egg-breakfasts/'
    | '/menu/hashbrown-bowls/'
    | '/menu/hashbrowns/'
    | '/menu/omelets/'
    | '/menu/sandwiches/'
    | '/menu/sides/'
    | '/menu/texas-melts/'
    | '/menu/waffles/'
    | '/menu/$category/page/$page'
    | '/menu/all-star-special/page/$page'
    | '/menu/beverages/page/$page'
    | '/menu/breakfast-sandwiches/page/$page'
    | '/menu/hashbrowns/page/$page'
    | '/menu/sides/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FaqRoute: typeof FaqRoute
  MenuRoute: typeof MenuRouteWithChildren
  MethodologyRoute: typeof MethodologyRoute
  NutritionRoute: typeof NutritionRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SearchRoute: typeof SearchRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCreatePostRoute: typeof AdminCreatePostRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  LocationsStateCityRoute: typeof LocationsStateCityRoute
  LocationsStateIndexRoute: typeof LocationsStateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-post': {
      id: '/admin/create-post'
      path: '/admin/create-post'
      fullPath: '/admin/create-post'
      preLoaderRoute: typeof AdminCreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/': {
      id: '/author/'
      path: '/author'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/$category': {
      id: '/menu/$category'
      path: '/$category'
      fullPath: '/menu/$category'
      preLoaderRoute: typeof MenuCategoryRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/beverages': {
      id: '/menu/beverages'
      path: '/beverages'
      fullPath: '/menu/beverages'
      preLoaderRoute: typeof MenuBeveragesRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/biscuits': {
      id: '/menu/biscuits'
      path: '/biscuits'
      fullPath: '/menu/biscuits'
      preLoaderRoute: typeof MenuBiscuitsRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/burgers': {
      id: '/menu/burgers'
      path: '/burgers'
      fullPath: '/menu/burgers'
      preLoaderRoute: typeof MenuBurgersRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/classic-dinners': {
      id: '/menu/classic-dinners'
      path: '/classic-dinners'
      fullPath: '/menu/classic-dinners'
      preLoaderRoute: typeof MenuClassicDinnersRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/hashbrowns': {
      id: '/menu/hashbrowns'
      path: '/hashbrowns'
      fullPath: '/menu/hashbrowns'
      preLoaderRoute: typeof MenuHashbrownsRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/sandwiches': {
      id: '/menu/sandwiches'
      path: '/sandwiches'
      fullPath: '/menu/sandwiches'
      preLoaderRoute: typeof MenuSandwichesRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/sides': {
      id: '/menu/sides'
      path: '/sides'
      fullPath: '/menu/sides'
      preLoaderRoute: typeof MenuSidesRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/texas-melts': {
      id: '/menu/texas-melts'
      path: '/texas-melts'
      fullPath: '/menu/texas-melts'
      preLoaderRoute: typeof MenuTexasMeltsRouteImport
      parentRoute: typeof MenuRoute
    }
    '/locations/$state/': {
      id: '/locations/$state/'
      path: '/locations/$state'
      fullPath: '/locations/$state/'
      preLoaderRoute: typeof LocationsStateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$state/$city': {
      id: '/locations/$state/$city'
      path: '/locations/$state/$city'
      fullPath: '/locations/$state/$city'
      preLoaderRoute: typeof LocationsStateCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$category/': {
      id: '/menu/$category/'
      path: '/'
      fullPath: '/menu/$category/'
      preLoaderRoute: typeof MenuCategoryIndexRouteImport
      parentRoute: typeof MenuCategoryRoute
    }
    '/menu/$category/$slug': {
      id: '/menu/$category/$slug'
      path: '/$slug'
      fullPath: '/menu/$category/$slug'
      preLoaderRoute: typeof MenuCategorySlugRouteImport
      parentRoute: typeof MenuCategoryRoute
    }
    '/menu/all-star-special/': {
      id: '/menu/all-star-special/'
      path: '/all-star-special'
      fullPath: '/menu/all-star-special/'
      preLoaderRoute: typeof MenuAllStarSpecialIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/beverages/': {
      id: '/menu/beverages/'
      path: '/'
      fullPath: '/menu/beverages/'
      preLoaderRoute: typeof MenuBeveragesIndexRouteImport
      parentRoute: typeof MenuBeveragesRoute
    }
    '/menu/biscuits/': {
      id: '/menu/biscuits/'
      path: '/'
      fullPath: '/menu/biscuits/'
      preLoaderRoute: typeof MenuBiscuitsIndexRouteImport
      parentRoute: typeof MenuBiscuitsRoute
    }
    '/menu/breakfast-sandwiches/': {
      id: '/menu/breakfast-sandwiches/'
      path: '/breakfast-sandwiches'
      fullPath: '/menu/breakfast-sandwiches/'
      preLoaderRoute: typeof MenuBreakfastSandwichesIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/breakfast/': {
      id: '/menu/breakfast/'
      path: '/breakfast'
      fullPath: '/menu/breakfast/'
      preLoaderRoute: typeof MenuBreakfastIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/burgers/': {
      id: '/menu/burgers/'
      path: '/'
      fullPath: '/menu/burgers/'
      preLoaderRoute: typeof MenuBurgersIndexRouteImport
      parentRoute: typeof MenuBurgersRoute
    }
    '/menu/classic-dinners/': {
      id: '/menu/classic-dinners/'
      path: '/'
      fullPath: '/menu/classic-dinners/'
      preLoaderRoute: typeof MenuClassicDinnersIndexRouteImport
      parentRoute: typeof MenuClassicDinnersRoute
    }
    '/menu/egg-breakfasts/': {
      id: '/menu/egg-breakfasts/'
      path: '/egg-breakfasts'
      fullPath: '/menu/egg-breakfasts/'
      preLoaderRoute: typeof MenuEggBreakfastsIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/hashbrown-bowls/': {
      id: '/menu/hashbrown-bowls/'
      path: '/hashbrown-bowls'
      fullPath: '/menu/hashbrown-bowls/'
      preLoaderRoute: typeof MenuHashbrownBowlsIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/hashbrowns/': {
      id: '/menu/hashbrowns/'
      path: '/'
      fullPath: '/menu/hashbrowns/'
      preLoaderRoute: typeof MenuHashbrownsIndexRouteImport
      parentRoute: typeof MenuHashbrownsRoute
    }
    '/menu/omelets/': {
      id: '/menu/omelets/'
      path: '/omelets'
      fullPath: '/menu/omelets/'
      preLoaderRoute: typeof MenuOmeletsIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/sandwiches/': {
      id: '/menu/sandwiches/'
      path: '/'
      fullPath: '/menu/sandwiches/'
      preLoaderRoute: typeof MenuSandwichesIndexRouteImport
      parentRoute: typeof MenuSandwichesRoute
    }
    '/menu/sides/': {
      id: '/menu/sides/'
      path: '/'
      fullPath: '/menu/sides/'
      preLoaderRoute: typeof MenuSidesIndexRouteImport
      parentRoute: typeof MenuSidesRoute
    }
    '/menu/texas-melts/': {
      id: '/menu/texas-melts/'
      path: '/'
      fullPath: '/menu/texas-melts/'
      preLoaderRoute: typeof MenuTexasMeltsIndexRouteImport
      parentRoute: typeof MenuTexasMeltsRoute
    }
    '/menu/waffles/': {
      id: '/menu/waffles/'
      path: '/waffles'
      fullPath: '/menu/waffles/'
      preLoaderRoute: typeof MenuWafflesIndexRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/$category/page/$page': {
      id: '/menu/$category/page/$page'
      path: '/page/$page'
      fullPath: '/menu/$category/page/$page'
      preLoaderRoute: typeof MenuCategoryPagePageRouteImport
      parentRoute: typeof MenuCategoryRoute
    }
    '/menu/all-star-special/page/$page': {
      id: '/menu/all-star-special/page/$page'
      path: '/all-star-special/page/$page'
      fullPath: '/menu/all-star-special/page/$page'
      preLoaderRoute: typeof MenuAllStarSpecialPagePageRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/beverages/page/$page': {
      id: '/menu/beverages/page/$page'
      path: '/page/$page'
      fullPath: '/menu/beverages/page/$page'
      preLoaderRoute: typeof MenuBeveragesPagePageRouteImport
      parentRoute: typeof MenuBeveragesRoute
    }
    '/menu/breakfast-sandwiches/page/$page': {
      id: '/menu/breakfast-sandwiches/page/$page'
      path: '/breakfast-sandwiches/page/$page'
      fullPath: '/menu/breakfast-sandwiches/page/$page'
      preLoaderRoute: typeof MenuBreakfastSandwichesPagePageRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/hashbrowns/page/$page': {
      id: '/menu/hashbrowns/page/$page'
      path: '/page/$page'
      fullPath: '/menu/hashbrowns/page/$page'
      preLoaderRoute: typeof MenuHashbrownsPagePageRouteImport
      parentRoute: typeof MenuHashbrownsRoute
    }
    '/menu/sides/page/$page': {
      id: '/menu/sides/page/$page'
      path: '/page/$page'
      fullPath: '/menu/sides/page/$page'
      preLoaderRoute: typeof MenuSidesPagePageRouteImport
      parentRoute: typeof MenuSidesRoute
    }
  }
}

interface MenuCategoryRouteChildren {
  MenuCategorySlugRoute: typeof MenuCategorySlugRoute
  MenuCategoryIndexRoute: typeof MenuCategoryIndexRoute
  MenuCategoryPagePageRoute: typeof MenuCategoryPagePageRoute
}

const MenuCategoryRouteChildren: MenuCategoryRouteChildren = {
  MenuCategorySlugRoute: MenuCategorySlugRoute,
  MenuCategoryIndexRoute: MenuCategoryIndexRoute,
  MenuCategoryPagePageRoute: MenuCategoryPagePageRoute,
}

const MenuCategoryRouteWithChildren = MenuCategoryRoute._addFileChildren(
  MenuCategoryRouteChildren,
)

interface MenuBeveragesRouteChildren {
  MenuBeveragesIndexRoute: typeof MenuBeveragesIndexRoute
  MenuBeveragesPagePageRoute: typeof MenuBeveragesPagePageRoute
}

const MenuBeveragesRouteChildren: MenuBeveragesRouteChildren = {
  MenuBeveragesIndexRoute: MenuBeveragesIndexRoute,
  MenuBeveragesPagePageRoute: MenuBeveragesPagePageRoute,
}

const MenuBeveragesRouteWithChildren = MenuBeveragesRoute._addFileChildren(
  MenuBeveragesRouteChildren,
)

interface MenuBiscuitsRouteChildren {
  MenuBiscuitsIndexRoute: typeof MenuBiscuitsIndexRoute
}

const MenuBiscuitsRouteChildren: MenuBiscuitsRouteChildren = {
  MenuBiscuitsIndexRoute: MenuBiscuitsIndexRoute,
}

const MenuBiscuitsRouteWithChildren = MenuBiscuitsRoute._addFileChildren(
  MenuBiscuitsRouteChildren,
)

interface MenuBurgersRouteChildren {
  MenuBurgersIndexRoute: typeof MenuBurgersIndexRoute
}

const MenuBurgersRouteChildren: MenuBurgersRouteChildren = {
  MenuBurgersIndexRoute: MenuBurgersIndexRoute,
}

const MenuBurgersRouteWithChildren = MenuBurgersRoute._addFileChildren(
  MenuBurgersRouteChildren,
)

interface MenuClassicDinnersRouteChildren {
  MenuClassicDinnersIndexRoute: typeof MenuClassicDinnersIndexRoute
}

const MenuClassicDinnersRouteChildren: MenuClassicDinnersRouteChildren = {
  MenuClassicDinnersIndexRoute: MenuClassicDinnersIndexRoute,
}

const MenuClassicDinnersRouteWithChildren =
  MenuClassicDinnersRoute._addFileChildren(MenuClassicDinnersRouteChildren)

interface MenuHashbrownsRouteChildren {
  MenuHashbrownsIndexRoute: typeof MenuHashbrownsIndexRoute
  MenuHashbrownsPagePageRoute: typeof MenuHashbrownsPagePageRoute
}

const MenuHashbrownsRouteChildren: MenuHashbrownsRouteChildren = {
  MenuHashbrownsIndexRoute: MenuHashbrownsIndexRoute,
  MenuHashbrownsPagePageRoute: MenuHashbrownsPagePageRoute,
}

const MenuHashbrownsRouteWithChildren = MenuHashbrownsRoute._addFileChildren(
  MenuHashbrownsRouteChildren,
)

interface MenuSandwichesRouteChildren {
  MenuSandwichesIndexRoute: typeof MenuSandwichesIndexRoute
}

const MenuSandwichesRouteChildren: MenuSandwichesRouteChildren = {
  MenuSandwichesIndexRoute: MenuSandwichesIndexRoute,
}

const MenuSandwichesRouteWithChildren = MenuSandwichesRoute._addFileChildren(
  MenuSandwichesRouteChildren,
)

interface MenuSidesRouteChildren {
  MenuSidesIndexRoute: typeof MenuSidesIndexRoute
  MenuSidesPagePageRoute: typeof MenuSidesPagePageRoute
}

const MenuSidesRouteChildren: MenuSidesRouteChildren = {
  MenuSidesIndexRoute: MenuSidesIndexRoute,
  MenuSidesPagePageRoute: MenuSidesPagePageRoute,
}

const MenuSidesRouteWithChildren = MenuSidesRoute._addFileChildren(
  MenuSidesRouteChildren,
)

interface MenuTexasMeltsRouteChildren {
  MenuTexasMeltsIndexRoute: typeof MenuTexasMeltsIndexRoute
}

const MenuTexasMeltsRouteChildren: MenuTexasMeltsRouteChildren = {
  MenuTexasMeltsIndexRoute: MenuTexasMeltsIndexRoute,
}

const MenuTexasMeltsRouteWithChildren = MenuTexasMeltsRoute._addFileChildren(
  MenuTexasMeltsRouteChildren,
)

interface MenuRouteChildren {
  MenuCategoryRoute: typeof MenuCategoryRouteWithChildren
  MenuBeveragesRoute: typeof MenuBeveragesRouteWithChildren
  MenuBiscuitsRoute: typeof MenuBiscuitsRouteWithChildren
  MenuBurgersRoute: typeof MenuBurgersRouteWithChildren
  MenuClassicDinnersRoute: typeof MenuClassicDinnersRouteWithChildren
  MenuHashbrownsRoute: typeof MenuHashbrownsRouteWithChildren
  MenuSandwichesRoute: typeof MenuSandwichesRouteWithChildren
  MenuSidesRoute: typeof MenuSidesRouteWithChildren
  MenuTexasMeltsRoute: typeof MenuTexasMeltsRouteWithChildren
  MenuIndexRoute: typeof MenuIndexRoute
  MenuAllStarSpecialIndexRoute: typeof MenuAllStarSpecialIndexRoute
  MenuBreakfastSandwichesIndexRoute: typeof MenuBreakfastSandwichesIndexRoute
  MenuBreakfastIndexRoute: typeof MenuBreakfastIndexRoute
  MenuEggBreakfastsIndexRoute: typeof MenuEggBreakfastsIndexRoute
  MenuHashbrownBowlsIndexRoute: typeof MenuHashbrownBowlsIndexRoute
  MenuOmeletsIndexRoute: typeof MenuOmeletsIndexRoute
  MenuWafflesIndexRoute: typeof MenuWafflesIndexRoute
  MenuAllStarSpecialPagePageRoute: typeof MenuAllStarSpecialPagePageRoute
  MenuBreakfastSandwichesPagePageRoute: typeof MenuBreakfastSandwichesPagePageRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuCategoryRoute: MenuCategoryRouteWithChildren,
  MenuBeveragesRoute: MenuBeveragesRouteWithChildren,
  MenuBiscuitsRoute: MenuBiscuitsRouteWithChildren,
  MenuBurgersRoute: MenuBurgersRouteWithChildren,
  MenuClassicDinnersRoute: MenuClassicDinnersRouteWithChildren,
  MenuHashbrownsRoute: MenuHashbrownsRouteWithChildren,
  MenuSandwichesRoute: MenuSandwichesRouteWithChildren,
  MenuSidesRoute: MenuSidesRouteWithChildren,
  MenuTexasMeltsRoute: MenuTexasMeltsRouteWithChildren,
  MenuIndexRoute: MenuIndexRoute,
  MenuAllStarSpecialIndexRoute: MenuAllStarSpecialIndexRoute,
  MenuBreakfastSandwichesIndexRoute: MenuBreakfastSandwichesIndexRoute,
  MenuBreakfastIndexRoute: MenuBreakfastIndexRoute,
  MenuEggBreakfastsIndexRoute: MenuEggBreakfastsIndexRoute,
  MenuHashbrownBowlsIndexRoute: MenuHashbrownBowlsIndexRoute,
  MenuOmeletsIndexRoute: MenuOmeletsIndexRoute,
  MenuWafflesIndexRoute: MenuWafflesIndexRoute,
  MenuAllStarSpecialPagePageRoute: MenuAllStarSpecialPagePageRoute,
  MenuBreakfastSandwichesPagePageRoute: MenuBreakfastSandwichesPagePageRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FaqRoute: FaqRoute,
  MenuRoute: MenuRouteWithChildren,
  MethodologyRoute: MethodologyRoute,
  NutritionRoute: NutritionRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SearchRoute: SearchRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCreatePostRoute: AdminCreatePostRoute,
  BlogSlugRoute: BlogSlugRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  LocationsStateCityRoute: LocationsStateCityRoute,
  LocationsStateIndexRoute: LocationsStateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
